/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcGeneric"
 * 	found in "cpm_asn/dsrc/ISO14906(2018)EfcDsrcGenericv7-patched.asn"
 * 	`asn1c -no-gen-example -no-gen-OER -pdu=auto -fincludes-quoted -fcompound-names`
 */

#ifndef	_AttributeList_H_
#define	_AttributeList_H_


#include "asn_application.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeList_H_ */
#include "asn_internal.h"
