/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "cpm_asn/dsrc/ISO-TS-19091-addgrp-C-2018_itse.asn"
 * 	`asn1c -no-gen-example -no-gen-OER -pdu=auto -fincludes-quoted -fcompound-names`
 */

#ifndef	_HeadingConfidenceitse_H_
#define	_HeadingConfidenceitse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HeadingConfidenceitse {
	HeadingConfidenceitse_unavailable	= 0,
	HeadingConfidenceitse_prec10deg	= 1,
	HeadingConfidenceitse_prec05deg	= 2,
	HeadingConfidenceitse_prec01deg	= 3,
	HeadingConfidenceitse_prec0_1deg	= 4,
	HeadingConfidenceitse_prec0_05deg	= 5,
	HeadingConfidenceitse_prec0_01deg	= 6,
	HeadingConfidenceitse_prec0_0125deg	= 7
} e_HeadingConfidenceitse;

/* HeadingConfidenceitse */
typedef long	 HeadingConfidenceitse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HeadingConfidenceitse;
asn_struct_free_f HeadingConfidenceitse_free;
asn_struct_print_f HeadingConfidenceitse_print;
asn_constr_check_f HeadingConfidenceitse_constraint;
ber_type_decoder_f HeadingConfidenceitse_decode_ber;
der_type_encoder_f HeadingConfidenceitse_encode_der;
xer_type_decoder_f HeadingConfidenceitse_decode_xer;
xer_type_encoder_f HeadingConfidenceitse_encode_xer;
per_type_decoder_f HeadingConfidenceitse_decode_uper;
per_type_encoder_f HeadingConfidenceitse_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HeadingConfidenceitse_H_ */
#include "asn_internal.h"
