/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "cpm_asn/dsrc/ISO-TS-19091-addgrp-C-2018_itse.asn"
 * 	`asn1c -no-gen-example -no-gen-OER -pdu=auto -fincludes-quoted -fcompound-names`
 */

#ifndef	_SpeedConfidenceitse_H_
#define	_SpeedConfidenceitse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SpeedConfidenceitse {
	SpeedConfidenceitse_unavailable	= 0,
	SpeedConfidenceitse_prec100ms	= 1,
	SpeedConfidenceitse_prec10ms	= 2,
	SpeedConfidenceitse_prec5ms	= 3,
	SpeedConfidenceitse_prec1ms	= 4,
	SpeedConfidenceitse_prec0_1ms	= 5,
	SpeedConfidenceitse_prec0_05ms	= 6,
	SpeedConfidenceitse_prec0_01ms	= 7
} e_SpeedConfidenceitse;

/* SpeedConfidenceitse */
typedef long	 SpeedConfidenceitse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeedConfidenceitse;
asn_struct_free_f SpeedConfidenceitse_free;
asn_struct_print_f SpeedConfidenceitse_print;
asn_constr_check_f SpeedConfidenceitse_constraint;
ber_type_decoder_f SpeedConfidenceitse_decode_ber;
der_type_encoder_f SpeedConfidenceitse_encode_der;
xer_type_decoder_f SpeedConfidenceitse_decode_xer;
xer_type_encoder_f SpeedConfidenceitse_encode_xer;
per_type_decoder_f SpeedConfidenceitse_decode_uper;
per_type_encoder_f SpeedConfidenceitse_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedConfidenceitse_H_ */
#include "asn_internal.h"
