/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "cpm_asn/dsrc/ISO14906(2018)EfcDsrcApplicationv6-patched_itse.asn"
 * 	`asn1c -no-gen-example -no-gen-OER -pdu=auto -fincludes-quoted -fcompound-names`
 */

#ifndef	_StationTypeitse_H_
#define	_StationTypeitse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StationTypeitse {
	StationTypeitse_unspecified	= 0,
	StationTypeitse_closedEntryWithPayment	= 1,
	StationTypeitse_closedEntryWithoutPayment	= 2,
	StationTypeitse_closedTransit	= 3,
	StationTypeitse_closedExit	= 4,
	StationTypeitse_closedCredit	= 5,
	StationTypeitse_mixed	= 6,
	StationTypeitse_passage	= 7,
	StationTypeitse_checkpoint	= 8,
	StationTypeitse_reload	= 9,
	StationTypeitse_reservedForFutureCENUse1	= 10,
	StationTypeitse_reservedForFutureCENUse2	= 11,
	StationTypeitse_reservedForFutureCENUse3	= 12,
	StationTypeitse_reservedForFutureCENUse4	= 13,
	StationTypeitse_privateUse5	= 14,
	StationTypeitse_privateUse6	= 15
} e_StationTypeitse;

/* StationTypeitse */
typedef long	 StationTypeitse_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_StationTypeitse_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_StationTypeitse;
extern const asn_INTEGER_specifics_t asn_SPC_StationTypeitse_specs_1;
asn_struct_free_f StationTypeitse_free;
asn_struct_print_f StationTypeitse_print;
asn_constr_check_f StationTypeitse_constraint;
ber_type_decoder_f StationTypeitse_decode_ber;
der_type_encoder_f StationTypeitse_encode_der;
xer_type_decoder_f StationTypeitse_decode_xer;
xer_type_encoder_f StationTypeitse_encode_xer;
per_type_decoder_f StationTypeitse_decode_uper;
per_type_encoder_f StationTypeitse_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _StationTypeitse_H_ */
#include "asn_internal.h"
