/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "cpm_asn/CPM.asn1"
 * 	`asn1c -no-gen-example -no-gen-OER -pdu=auto -fincludes-quoted -fcompound-names`
 */

#ifndef	_TimeOfMeasurement_H_
#define	_TimeOfMeasurement_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeOfMeasurement {
	TimeOfMeasurement_oneMilliSecond	= 1
} e_TimeOfMeasurement;

/* TimeOfMeasurement */
typedef long	 TimeOfMeasurement_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TimeOfMeasurement_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TimeOfMeasurement;
asn_struct_free_f TimeOfMeasurement_free;
asn_struct_print_f TimeOfMeasurement_print;
asn_constr_check_f TimeOfMeasurement_constraint;
ber_type_decoder_f TimeOfMeasurement_decode_ber;
der_type_encoder_f TimeOfMeasurement_encode_der;
xer_type_decoder_f TimeOfMeasurement_decode_xer;
xer_type_encoder_f TimeOfMeasurement_encode_xer;
per_type_decoder_f TimeOfMeasurement_decode_uper;
per_type_encoder_f TimeOfMeasurement_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeOfMeasurement_H_ */
#include "asn_internal.h"
