/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "cpm_asn/dsrc/ISO14906(2018)EfcDsrcApplicationv6-patched_itse.asn"
 * 	`asn1c -no-gen-example -no-gen-OER -pdu=auto -fincludes-quoted -fcompound-names`
 */

#ifndef	_VehicleTotalDistance_H_
#define	_VehicleTotalDistance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Int4.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleTotalDistance */
typedef Int4_t	 VehicleTotalDistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleTotalDistance;
asn_struct_free_f VehicleTotalDistance_free;
asn_struct_print_f VehicleTotalDistance_print;
asn_constr_check_f VehicleTotalDistance_constraint;
ber_type_decoder_f VehicleTotalDistance_decode_ber;
der_type_encoder_f VehicleTotalDistance_encode_der;
xer_type_decoder_f VehicleTotalDistance_decode_xer;
xer_type_encoder_f VehicleTotalDistance_encode_xer;
per_type_decoder_f VehicleTotalDistance_decode_uper;
per_type_encoder_f VehicleTotalDistance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleTotalDistance_H_ */
#include "asn_internal.h"
